[build]
  publish =  "dist/"
  command = "yarn run build.func && yarn run build.prod"
  functions = "functions"

[context.production]
  environment = { }

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=21600"
