[build]
  publish =  "dist/"
  command = "sh netlify-build.sh"
  functions = "functions"

[context.production]
  environment = { }

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200