[build]
  publish =  "dist/"
  command = "sh netlify-build.sh"
  functions = "functions"

[context.production]
  environment = { }

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=21600"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200